---
components:
  - component:
      name: battery
      path: qpylibs\base\battery
      version: v0.0.2
  - component:
      name: ADC
      path: qpylibs\base\bus\ADC
      version: v0.0.1
  - component:
      name: GPIO
      path: qpylibs\base\bus\GPIO
      version: v0.0.1
  - component:
      name: PWM
      path: qpylibs\base\bus\PWM
      version: v0.0.1
  - component:
      name: SPI
      path: qpylibs\base\bus\SPI
      version: v0.0.1
  - component:
      name: EventMessage
      path: qpylibs\base\EventMessage
      version: v0.0.1
  - component:
      name: led
      path: qpylibs\base\led
      version: v0.0.1
  - component:
      name: loop
      path: qpylibs\base\loop
      version: v0.0.1
  - component:
      name: queue
      path: qpylibs\base\queue
      version: v0.0.1
  - component:
      name: sys_bus
      path: qpylibs\base\sys_bus
      version: v0.0.1
  - component:
      name: watchdog
      path: qpylibs\base\watchdog
      version: v0.0.1
  - component:
      name: camera
      path: qpylibs\peripheral\camera
      version: v0.0.1
  - component:
      name: TM1650
      path: qpylibs\peripheral\DigitalTube\TM1650
      version: v0.0.1
  - component:
      name: ili9225
      path: qpylibs\peripheral\display\ili9225
      version: v0.0.1
  - component:
      name: ili9341
      path: qpylibs\peripheral\display\ili9341
      version: v0.0.1
  - component:
      name: st7735
      path: qpylibs\peripheral\display\st7735
      version: v0.0.1
  - component:
      name: st7789
      path: qpylibs\peripheral\display\st7789
      version: v0.0.1
  - component:
      name: dm9051
      path: qpylibs\peripheral\Ethernet\dm9051
      version: v0.0.1
  - component:
      name: sdcard
      path: qpylibs\peripheral\ExStorage\sdcard
      version: v0.0.1
  - component:
      name: L67K
      path: qpylibs\peripheral\GNSS\L67K
      version: v0.0.1
  - component:
      name: ADXL346
      path: qpylibs\peripheral\GSensor\ADXL346
      version: v0.0.1
  - component:
      name: bma250
      path: qpylibs\peripheral\GSensor\bma250
      version: v0.0.1
  - component:
      name: lis2dh12
      path: qpylibs\peripheral\GSensor\lis2dh12
      version: v0.0.1
  - component:
      name: aht10
      path: qpylibs\peripheral\HTSensor\aht10
      version: v0.0.1
  - component:
      name: aht20
      path: qpylibs\peripheral\HTSensor\aht20
      version: v0.0.1
  - component:
      name: HDC1080
      path: qpylibs\peripheral\HTSensor\HDC1080
      version: v0.0.1
  - component:
      name: HDC2080
      path: qpylibs\peripheral\HTSensor\HDC2080
      version: v0.0.1
  - component:
      name: ch423s
      path: qpylibs\peripheral\IoExpend\ch423s
      version: v0.0.1
  - component:
      name: MCP23017
      path: qpylibs\peripheral\IoExpend\MCP23017
      version: v0.0.1
  - component:
      name: gl5516
      path: qpylibs\peripheral\LightSensor\gl5516
      version: v0.0.1
  - component:
      name: gl5528
      path: qpylibs\peripheral\LightSensor\gl5528
      version: v0.0.1
  - component:
      name: GY-302
      path: qpylibs\peripheral\LightSensor\GY-302
      version: v0.0.1
  - component:
      name: OPT3001
      path: qpylibs\peripheral\LightSensor\OPT3001
      version: v0.0.1
  - component:
      name: BL0939
      path: qpylibs\peripheral\MeteringChip\BL0939
      version: v0.0.1
  - component:
      name: HLW8110
      path: qpylibs\peripheral\MeteringChip\HLW8110
      version: v0.0.1
  - component:
      name: mfrc522
      path: qpylibs\peripheral\NFC\mfrc522
      version: v0.0.1
  - component:
      name: aw8733
      path: qpylibs\peripheral\PowerAmplifier\aw8733
      version: v0.0.1
  - component:
      name: RDA5807
      path: qpylibs\peripheral\radio\RDA5807
      version: v0.0.1
  - component:
      name: poc
      path: qpylibs\peripheral\Talkie\poc
      version: v0.0.1
  - component:
      name: esp8266
      path: qpylibs\peripheral\WIFI\esp8266
      version: v0.0.1
  - component:
      name: ctwing
      path: qpylibs\platform\cloud\ctwing
      version: v0.0.1
  - component:
      name: onenet
      path: qpylibs\platform\cloud\onenet
      version: v0.0.1
  - component:
      name: quecthing
      path: qpylibs\platform\cloud\quecthing
      version: v0.0.1
  - component:
      name: ntp
      path: qpylibs\platform\protocol\ntp
      version: v0.0.1
